### PR TITLE
Fixes related to cache clear and concurrent promises

### PR DESCRIPTION
**Pull request by slightlytyler**
Found a bug while trying to write some tests for components using SWR. `cache.clear()` doesn't clear the concurrent promises so further calls get stuck in the suspense fallback (not quite sure why that's the resulting behavior).  Simply iterating through the concurrent promises and deleting entries fixes the problem. 

Also had to update react testing library and JSDOM, otherwise the tests pass incorrectly (pretty sure this isn't a bug in either of those libraries). The JSDOM changes the required node version to > 10 to develop the project though

### CODE REVIEW

**Comment by slightlytyler** [comment]
Something to note is that I'm aware of discussion like https://github.com/zeit/swr/pull/326  and `dedupingInterval` but from my testing that doesn't solve the problem

**Comment by slightlytyler** [comment]
For reference here is an example test that was failing before this change
```js
import React from 'react';
import { cache } from 'swr';
import { render, waitFor } from '@testing-library/react';
import SomeComponent from './SomeComponent;
import mockedHttpClient from './mockedHttpClient';

describe('container error handling', () => {
  afterEach(() => {
    cache.clear();
  });

  it('should render a homepage at the root url', async () => {
    const { queryByText } = render(<SomeComponent />);
    await waitFor(() => expect(queryByText(/some title/i)).toBeVisible());
  });

  it('should render an error message when srosh is 500ing', async () => {
    mockedHttpClient.onGet('/some_path').replyOnce(500);
    const { queryByText } = render(<SomeComponent />);
    await waitFor(() => expect(queryByText(/error boundary text/i)).toBeVisible());
    expect(queryByText(/title/i)).toBeNull();
  });
});
```

**Comment by shuding** [comment]
Thank you for this amazing PR @slightlytyler! I think I'll look deeper into this because from my understanding, the concurrent promises will be removed right after throwing to <Suspense>, if you have `dedupingInterval` set to 0. So this seems like another bug.

**Comment by slightlytyler** [comment]
@shuding you're write I think, after looking again I found a bug with how deduping interval was handled https://github.com/zeit/swr/pull/335/files#diff-ab20307c185620c9b54994fa4dcee1b7R270

my change there fixes a part of the failing test I added but it doesn't completely pass yet

**Comment by slightlytyler** [comment]
Been messing with it for a while and still can't quite narrow the source of the race conditions. Different values in the timeouts produce different failures so pretty sure it's a race condition with concurrent promises beyond the initial one I mentioned

**Comment by slightlytyler** [comment]
Looking again and seems like the problem is that on initial mount `revalidate` is called twice. Once as a hard revalidation then again as a soft revalidation. The soft revalidation fails the `shouldDeduping` check since concurrent promises have already been removed from the deduping timeout. Instead the soft revalidation get's processed as a hard revalidation, and resets concurrent promises

I don't think this produces a bug in the real behavior but it totally messes with tests

**Comment by slightlytyler** [comment]
Finally got something to  pass  the tests. Basic idea is that  you tracker a counter `cache.version`, clear increments it, and then in the hook we check for a mismatch in  `revalidate` and  throw away updates that fail the check. `cache.clear` also synchronously removes concurrent promises

Not sure if these are the right patterns but I think the test case is valid

Anyways, love SWR, hope I can help you get this solved 👍

**Comment by alexl0gan** [comment]
My team are also having the same issue. Any progress on this pr @slightlytyler @shuding ?

**Comment by slightlytyler** [comment]
@alexl0gan not working on a project that uses SWR anymore but I think react-query's `ReactQueryCacheProvider` is a better way to solve this problem then trying to manipulate the singleton cache synchronously in tests. Closing this as I'm sure it's useless to the project at this point

**Comment by kristojorg** [comment]
@slightlytyler I don't think this is useless to the project... I'm still facing the same issue

**Comment by kristojorg** [comment]
I've resorted to mocking SWR entirely to resolve this, for anyone else looking

**Pull request closed without merging**
