### PR TITLE
Micro optimizations

### PR DESCRIPTION
**Pull request by shuding**
Make the code cleaner and more consistent:
- use the `useState({})[1]` pattern for re-rendering the component
- make the internal property names shorter in `Cache`
- make the key prefixes in useSWRInfinite 3 chars (`ctx@`, `inf@`, `len@`), and internal cache property name shorter
- make `addRevalidator` return the ubsubscriber

Closes #896.

### CODE REVIEW

**Review by huozhi — APPROVED** [review]
generally lgtm. the lint warning is a fake one. disabling it or rollback to array destruction are both acceptable.
eslint hooks ignore the none array pattern for useState, haven't found any useful case to work around yet

**Comment by shuding** [comment]
@huozhi It seems like the linter didn't yell, so I think it's fine :)

**Comment by ranisalt** [comment]
@shuding care to point out what is the `useState({})[1]` trick? I'm curious on what it changes.

**Comment by shuding** [comment]
@ranisalt it's an implementation detail inside SWR, previously we are using `const [,rerender] = useState(false)` to create a re-render function, now it uses `const rerender = useState({})[1]`.

**Pull request merged**
