### PR TITLE
Return '@null' if args is null ASAP

### PR DESCRIPTION
**Pull request by matamatanot**
If args[i] is null, always return `@null`.

Now, check `typeof args[i] === 'string'` and run `String(args[i])`. This is unnecessary.
This fix should improve readability and speed by a small amount.

### CODE REVIEW

**Comment by matamatanot** [comment]
I have committed into `vercel:master`. Was `vercel:next` more appropriate? 
I'm skipping the error on ts-ignore using` --no-verify`. It seems to have already been fixed in `vercel:next`.

**Comment by shuding** [comment]
@matamatanot yeah if it’s not a breaking change please target master. `next` is for 1.0 👍

**Comment by matamatanot** [comment]
There is an error. The cause is #754.

**Comment by shuding** [comment]
So this changes the hook behavior:

Before:
```js
useSWR([1, 2, null, 3, 4]) // => key will be `arg@1@2@null@3@4`
```

Now:
```js
useSWR([1, 2, null, 3, 4]) // => key will be `arg@1@2@null`
```

I think that feels inconsistent and may also cause key conflicts. But it is indeed a good question: should we skip the request if **one of the args** is `null`...?

**Comment by matamatanot** [comment]
@shuding 
I mistook `for` for `forEach`. Is it from a performance perspective that used `for`?

**Comment by matamatanot** [comment]
This is an example of using `reduce`. It's not clear if it improved readability and performance. Instead, it may be worse.

```
function hash2(args: any[]): string {
  if (!args.length) return ''
  return args.reduce((acc: string, current: any) => {
    if (current === null) {
      return (acc += '@null')
    } else if (typeof current !== 'object' && typeof current !== 'function') {
      if (typeof current === 'string') {
        return (acc += '@' + '"' + current + '"')
      } else {
        return (acc += '@' + String(current))
      }
    } else {
      if (!table.has(current)) {
        table.set(current, counter++)
        return (acc += '@' + (counter - 1))
      } else {
        return (acc += '@' + table.get(current))
      }
    }
  }, 'arg')
}
```

**Comment by shuding** [comment]
Yeah I think as a small util, it's better to use `for` due to performance.

**Comment by matamatanot** [comment]
Using the continue statement. If you don't find it useful, you can close this.

**Review by shuding — APPROVED** [review]
Thanks!

**Pull request merged**
