### PR TITLE
Fix suspense

### LINKED ISSUE #494: React experimental concurrent issue
https://github.com/facebook/react/pull/18838

I tried `swr` with suspense mode, with a recent `0.0.0-experimental-7f28234f8` react build, and I get errors `Can't perform a React state update on a component that hasn't mounted yet` for each `useSWR` call.

> This indicates that there's a side-effect spawned during render, that then asynchronously tries to set state when the response comes back. E.g. kick off a request and then setState with the result. It's a common mistake when implementing Suspense.

> This should be done in useEffect.

Does this make sense to you?

Unfortunately I can't help you a lot more than that, it doesn't help to where the error comes exactly.

### PR DESCRIPTION
**Pull request by promer94**
fix #494

### CODE REVIEW

**Comment by promer94** [comment]
https://codesandbox.io/s/swr-494-ievc8

**Review by shuding — COMMENTED** [review]
Thanks for the fix! Can confirm that error is gone. (BTW I suggest renaming this ref to `initialMountedRef`)

**Review by shuding — APPROVED** [review]

**Comment by huozhi** [comment]
> Thanks for the fix! Can confirm that error is gone. (BTW I suggest renaming this ref to `initialMountedRef`, what do you think?)

yup the first unmountRef is kinda confused, not really for mount/unmount, but for dependency changes. maybe we can rename it later as well

**Comment by shuding** [comment]
@huozhi yep I agree 👍

**Pull request merged**
