### PR TITLE
Fix: type support for suspense and fallbackData(#2396)

### PR DESCRIPTION
**Pull request by taro-28**
close https://github.com/vercel/swr/issues/2396

### CODE REVIEW

**Comment by huozhi** [comment]
Thanks for the PR, can you add some typing tests for it?

**Comment by taro-28** [comment]
I understand, I'll try it!

**Review by huozhi — APPROVED** [review]
Thanks!

**Comment by nstepien** [comment]
This would be a huge fix for us! 🎉 Can we expect a swr release soon?

**Pull request merged**
