### PR TITLE
fix: allow onErrorRetry on inactive tab without focus/reconnect revalidation

### PR DESCRIPTION
**Pull request by qkdreyer**
fix: #2543

### CODE REVIEW

**Comment by qkdreyer** [comment]
@shuding @huozhi bump?

**Comment by qkdreyer** [comment]
@shuding @huozhi bump 🙏

**Comment by potemkin-git** [comment]
Any news about this ?
Seems very handy 🙏

**Review by shuding — APPROVED** [review]
Thanks!

**Comment by shuding** [comment]
There’s a merge conflict, could you have it fixed?

**Comment by AlexViard** [comment]
Any chance for this PR to be merged soon ? 
I really need it.

**Comment by BBEN17** [comment]
Yo, 
Could we expect this PR to get merged soon?
It could realy help me to resolve my pb

Thx !

**Comment by benoit115** [comment]
@huozhi can you please go ahead? Thanks 🙏

**Pull request merged**
