### PR TITLE
refactor: revalidateIfStale has an effect on updates, not only mounting

### PR DESCRIPTION
**Pull request by koba04**
Please correct me if I'm wrong 🙏

The documentation of `revalidateIfStale` says that "automatic revalidation on mount even if there is stale data", but according to the current implementation, the `revalidateIfStale` option has an effect on updates, doesn't it?

https://swr.vercel.app/docs/options#options

If so, I'll send a PR for that.

In this PR,  I made three changes that I've noticed while reading the implementation.

1. The [`shouldRevalidateOnMount`](https://github.com/vercel/swr/blob/c63cafcb00f78af1d16ef5649d7c26d396c46de9/src/use-swr.ts#L446) function has an effect on updates, not only mounting. So I feel `shouldRevalidate` is the appropriate name for the function.

2. In the `shouldRevalidate` function, the `revalidateOnMount` option should be changed only when mounting, so I've added the condition.

3. The `keyChanged` variable should be `true` when `key` has been changed or initial mount. `key` is always changed when mounting, so `key !== keyRef.current` meets the condition.

### CODE REVIEW

**Comment by koba04** [comment]
I've created a demo for this.
https://codesandbox.io/s/awesome-butterfly-6gkrr

**Review by shuding — APPROVED** [review]
Thank you for the refactoring, and totally agreed with all the 3 points you raised! However I’m not seeing anything wrong in your demo (it should be the expected behavior for `revalidateIfStale`), maybe I’m missing something?

**Comment by shuding** [comment]
Oh I just saw your PR for the docs – good catch!

**Comment by koba04** [comment]
Thank you!
I've marked this as `refactor`, but I've changed a current behavior of `revalidateOnMount`. `revalidateOnMount` now affects only on mount, so it might be better to add this into the changelog of the next release.

**Pull request merged**
