### PR TITLE
Tweak types

### PR DESCRIPTION
**Pull request by promer94**
* make ```useSWR<{ id: number }>('/api/', (key) => ({ id: 123 }))``` still works as before 
so users dont need to update their current code
* add test case for #1586 
* remove some comments (replace with ts playground link later)

### CODE REVIEW

**Review by huozhi — COMMENTED** [review]
> make useSWR<{ id: number }>('/api/', (key) => ({ id: 123 })) still works as before
Which issue is this item trying to resolve? Could you elabrate?

What's the purpose of exporting `OriginFetcher` and when will user use it?

**Comment by promer94** [comment]
> Which issue is this item trying to resolve? Could you elabrate?

Because the limitation of typescript. It could not support partial type argument inference

 ```typescript
// These two will works
useSWR<{ id: number }>('/api/', (key) => ({ id: 123 }))
useSWR<{ id: number }, any, string>('/api/', (key) => ({ id: 123 }))


useSWR<{ id: number }>('/api/', (key) => ({ id: 123 }))
// this would make fetcher's type fallback to 
// ((args_0: string) => FetcherResponse<boolean>) | ((args_0: any, ...args_1: unknown[]) => FetcherResponse<boolean>) | ((args_0: Record<any, any>) => FetcherResponse<...>) | ((args_0: string | ... 2 more ... | Record<...>) => FetcherResponse<...>) | null'
// it would cause type error

```
 
 

related issue https://github.com/vercel/swr/issues/1518#issue-1013082584  
real world problem https://github.com/vercel/swr/pull/1477#issuecomment-961845025 https://github.com/vercel/swr/issues/1621#issue-1045895828



> What's the purpose of exporting OriginFetcher

useSWRInfinite also uses this type

**Review by shuding — COMMENTED** [review]
Thanks, this looks like a great workaround! Can you add a test for the `Data` inference case you mentioned?

Also regarding `OriginFetcher` I think that `BareFetcher` might be a better name.

**Comment by shuding** [comment]
❤️

**Comment by huozhi** [comment]
Nice work! Thanks

**Pull request merged**
