### PR TITLE
[WIP] Subscribe mode

### PR DESCRIPTION
**Pull request by huozhi**
Draft solution to #728
To support subscription / disposable / observable data source, adding a new hook useSWRSubscription built on top of useSWR.

### API

```
useSWRSupscrition(key, subscribeFn: SWRSubscription, config?)
```

```ts
type SWRSubscription<Data> = (
  onData: (data: Data) => void,
  onError: (err: any) => void,
): () => void
```

the purpose is to provider users enough flexibility to manage their own subscription/disposable on user land, but still keep the argument shape different from function type fetcher.

### Usage

```js
const {data, error} = useSWRSubscription(key, (onData, onError) {
    const dispose = remoteDataSource.subscribe(onData, onError)
    return () => dispose()
 })
```

### CODE REVIEW

**Comment by followbl** [comment]
would be awesome to get this in - we'd use it right away!

**Comment by iamsaurabhgupt** [comment]
@huozhi @shuding @pacocoursey how far is this from getting into production?

**Comment by huozhi** [comment]
Close this to file another one with middleware implementation

**Comment by souljorje** [comment]
@huozhi hey! any updates about it?

**Comment by huozhi** [comment]
The implementation is moved to https://github.com/vercel/swr/pull/1263

**Pull request closed without merging**
