### PR TITLE
Update Cache Interface types

### PR DESCRIPTION
**Pull request by dmmulroy**
# Update Cache Interface types

## Update 04/08/23
Per discussion with @promer94, the solution outlined in [An Alternative Approach](#alternative-approach) has been implemented rather than updating the `keys` interface.

## Motivation & Background

As it's currently typed, the `Cache` interface that is required for users to create and provide their own cache implementations mandates that the `keys` method return an `IterableIterator<string>`. I believe this to be incorrectly typed, or at the very least, inconveniently typed and a burden for consumers. I think that the correct type should be `IterableIterator<Key>` given that the `get`, `set`, and `delete` methods all require a `Key` as input. 

Consider the [default implementation](https://github.com/vercel/swr/blob/main/_internal/utils/config.ts#L44) provided by `swr`:

```typescript
// Default cache provider
const [cache, mutate] = initCache(new Map()) as [Cache<any>, ScopedMutator<any>]
```
This is effectively the same as:

```typescript
const cacheMap: Cache<any> = new Map<Key, State<any, any>>()
const [cache, mutate] = initCache(cacheMap) as [Cache<any>, ScopedMutator<any>]
```
Which results in a type error:

```
Type 'Map<Key, State<any, any>>' is not assignable to type 'Cache<any>'.
     The types returned by 'keys()' are incompatible between these types.
       Type 'IterableIterator<Key>' is not assignable to type 'IterableIterator<string>'.
         Type 'Key' is not assignable to type 'string'.
           Type 'undefined' is not assignable to type 'string'.
```

This puts a burden on users/consumers of `swr` when implementing their own cache, especially if the underlying data structure is a `Map`. 

My use case is creating a custom LRU Cache to back `swr`, see the following gist for its implementation: https://gist.github.com/dmmulroy/33c31bef81554b099726b3a680dad974

Because `keys` is typed as `IterableIterator<string>` I have to cast.

```typescript
/**
   * Returns an iterable iterator over the keys in the cache.
   *
   * @returns {IterableIterator<string>} - An iterator of the cache keys.
   */
  public keys(): IterableIterator<string> {
    return this.cache.keys() as IterableIterator<string>
  }
```

## An Alternative Approach <a id="alternative-approach"></a>
An alternative approach would be to update the `Cache` interface to the following:

```typescript
export interface Cache<Data = any> {
  keys(): IterableIterator<string>
  get(key: string): State<Data> | undefined
  set(key: string, value: State<Data>): void
  delete(key: string): void
}
```

This actually may be more accurate and reflect what occurs at run time. As far as I can tell, any time the cache is accessed by `swr` internally the `key` is always serialized into a `string` via the `serialize`[^1] function prior to access. 

You can see that any time the cache is accessed[^2], it's accessed via callbacks returned from `createCacheHelper`[^3] in which the `SWRGlobalState` is referenced/retrieved and used get to the `setter` callback from `initCache`[^4] which is stored in global state. In all instances (you can search by reference to confirm), the `Getter` and `Setter` callbacks are passed `string` keys which have been serialized.

In addition, I believe this may actually be worth considering because `unstable_serialize`[^5] is publicly exported. I assume this is to aid consumers/users if they choose to directly access/mutate the cache (despite explicitly being called out in the docs as anti pattern[^6]) as seen in #2216. 

[^1]: https://github.com/vercel/swr/blob/main/_internal/utils/serialize.ts#L6
[^2]: [Getter Callback](https://github.com/vercel/swr/blob/main/_internal/utils/helper.ts#L39), [Setter Callback](https://github.com/vercel/swr/blob/main/_internal/utils/helper.ts#L41), [Previous value in Setter](https://github.com/vercel/swr/blob/main/_internal/utils/helper.ts#L43), [Setter Callback from SWRGlobalState](https://github.com/vercel/swr/blob/main/_internal/utils/cache.ts#L64)
[^3]: https://github.com/vercel/swr/blob/main/_internal/utils/helper.ts#L32
[^4]: https://github.com/vercel/swr/blob/main/_internal/utils/cache.ts#L26
[^5]: https://github.com/vercel/swr/blob/main/core/use-swr.ts#L679
[^6]: https://swr.vercel.app/docs/advanced/cache#modify-the-cache-data

### CODE REVIEW

**Comment by dmmulroy** [comment]
I also just noticed that [the docs are incorrect](https://swr.vercel.app/docs/advanced/cache#cache-provider) as well and list the type of `Cache` as the following:

```typescript
interface Cache<Data> {
  get(key: string): Data | undefined
  set(key: string, value: Data): void
  delete(key: string): void
  keys(): IterableIterator<string>
}
```

**Comment by promer94** [comment]
Thanks for the PR !

I think we should take the alternative approach here. 
It is more simple and the fact is that we only use string key here.

**Comment by dmmulroy** [comment]
Awesome - I'll be happy to make those changes and get them pushed up tomorrow or sunday.

**Comment by dmmulroy** [comment]
Changes have been made, take a look when you have the chance @promer94 🚀

**Review by promer94 — APPROVED** [review]
Thanks

**Pull request merged**
