### PR TITLE
fix: mutate args for useSWRInfinite hook

### PR DESCRIPTION
**Pull request by sanjeev29**
This PR fixes the bug mentioned in #1899. 

As mentioned in the documentation (https://swr.vercel.app/docs/pagination#return-values), mutate function returned by the useSWRInfinite hook should work the same as the useSWR hook.

### CODE REVIEW

**Review by shuding — COMMENTED** [review]
Thanks! Would you mind adding a test so we won't have regression in the future?

**Comment by sanjeev29** [comment]
@shuding Yes! Will do that.

**Comment by koba04** [comment]
@shuding 
Should the mutate function `useSWRInfinite` returns support the following options as well as the `revalidate` option?

- `optimisticData`
- `populateCache`
- `rollbackOnError`

https://swr.vercel.app/docs/mutation#optimistic-updates

If not, it would be nice to add the supported options to the documentation.

**Comment by shuding** [comment]
Yes, I think these should be supported by this hook too 👍

**Comment by sanjeev29** [comment]
@shuding Cool. Let me make a push for this!

**Comment by sanjeev29** [comment]
@shuding Kinda had a hard time writing a test for this using optimistic updates. Can you scope it out here?

**Review by koba04 — APPROVED** [review]

**Comment by koba04** [comment]
The following type also should be updated, but I think it's ok to fix it with [the following PR](https://github.com/vercel/swr/pull/1947#issuecomment-1115011415)
https://github.com/vercel/swr/blob/a3221302b3558a443f8cfa5d6e3dd27bb7c8f138/infinite/index.ts#L179

**Comment by sanjeev29** [comment]
@koba04 I can resolve these conflicts?

**Comment by shuding** [comment]
Thanks!

**Pull request merged**
