### PR TITLE
fix(infinte): export SWRInfiniteKeyedMutator type

### PR DESCRIPTION
**Pull request by LeoMcA**
https://github.com/vercel/swr/pull/2862/files added a new `InfiniteKeyedMutator` type, but didn't export it, which meant we had to use [a rather roundabout fix](https://github.com/mdn/yari/pull/10538/commits/e847feddf419e9680dbd7755d46c317a4027cd62):

```ts
// "swr/infinite" doesn't export InfiniteKeyedMutator directly
type InfiniteKeyedMutator<T> = SWRInfiniteResponse<
  T extends (infer I)[] ? I : T
>["mutate"];
```

It would be great if we could export this type directly, like `KeyedMutator` is.

### CODE REVIEW

**Comment by agjs** [comment]
Can we merge this?

**Comment by eifr** [comment]
any updates regarding this one? im unable to upgrade atm as im using `KeyedMutator` as prop

**Review by koba04 — APPROVED** [review]
Thank you!

**Comment by koba04** [comment]
I've changed the name to `SWRInfiniteKeyedMutator` for consistency

**Pull request merged**
